# Generated by Django 3.0.2 on 2021-01-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_category_one',
            fields=[
                ('category_one_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('category_one_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_category_three',
            fields=[
                ('category_three_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('category_three_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_category_two',
            fields=[
                ('category_two_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('category_two_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_question_category',
            fields=[
                ('question_category_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('question_category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='T_question_info',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_difficulty', models.CharField(max_length=4, null=True)),
                ('question_content', models.TextField()),
                ('right_option', models.CharField(max_length=4)),
                ('option_A', models.TextField()),
                ('option_B', models.TextField()),
                ('option_C', models.TextField(null=True)),
                ('option_D', models.TextField(null=True)),
                ('question_analysis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_question_type',
            fields=[
                ('question_type_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('question_type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='T_test_paper',
            fields=[
                ('test_paper_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('test_paper_name', models.CharField(max_length=50, null=True)),
                ('question_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_question_category')),
            ],
        ),
        migrations.CreateModel(
            name='T_test_info',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('question_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_question_category')),
                ('test_paper_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_test_paper')),
            ],
        ),
    ]
