# Generated by Django 3.0.2 on 2021-01-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_test_info',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='T_test_info.user_id+', to='User.T_user_info'),
        ),
        migrations.AddField(
            model_name='t_question_info',
            name='question_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_question_category'),
        ),
        migrations.AddField(
            model_name='t_question_info',
            name='question_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_question_type'),
        ),
        migrations.AddField(
            model_name='t_question_info',
            name='test_paper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_test_paper'),
        ),
    ]
