# Generated by Django 3.0.2 on 2021-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0002_auto_20210109_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_question_info',
            name='option_E',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='t_question_info',
            name='option_F',
            field=models.TextField(null=True),
        ),
    ]
