# Generated by Django 3.0.2 on 2021-01-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Examination', '0003_auto_20210109_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_category_one',
            name='category_one_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='t_category_three',
            name='category_three_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='t_category_two',
            name='category_two_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='t_question_info',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_question_info',
            name='question_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_question_type'),
        ),
        migrations.AlterField(
            model_name='t_question_info',
            name='test_paper_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_test_paper'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='test_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='test_paper_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_test_paper'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='T_test_info.user_id+', to='User.T_user_info'),
        ),
        migrations.AlterField(
            model_name='t_test_paper',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_test_paper',
            name='test_paper_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
