# Generated by Django 3.0.2 on 2021-01-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0004_auto_20210109_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_test_paper',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Examination.T_question_category'),
        ),
    ]
