# Generated by Django 3.0.2 on 2021-01-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210109_1700'),
        ('Examination', '0005_auto_20210109_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_test_info',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='T_test_info_user_id', to='User.T_user_info'),
        ),
        migrations.AlterField(
            model_name='t_test_paper',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_test_paper_question_category_id', to='Examination.T_question_category'),
        ),
    ]
