# Generated by Django 3.0.2 on 2021-01-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_user_info',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('wechat_id', models.CharField(max_length=32, null=True)),
                ('user_real_name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(default=0, max_length=11, null=True, unique=True)),
                ('identity_card', models.CharField(max_length=18, null=True, unique=True)),
                ('permission', models.CharField(max_length=1, null=True)),
                ('login_state', models.CharField(max_length=1, null=True)),
                ('registration_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_test_info',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField(null=True)),
                ('score', models.CharField(max_length=3, null=True)),
                ('question_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='Examination.T_question_category')),
                ('test_paper_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_paper', to='Examination.T_test_paper')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='User.T_user_info')),
            ],
        ),
        migrations.CreateModel(
            name='T_purchase_state',
            fields=[
                ('purchase_state_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(null=True)),
                ('current_state', models.CharField(default='0', max_length=10, null=True)),
                ('question_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_state_category_idcategory', to='Examination.T_question_category')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_state_user', to='User.T_user_info')),
            ],
        ),
        migrations.CreateModel(
            name='T_purchase_history',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(null=True)),
                ('question_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_history_category_id', to='Examination.T_question_category')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_history_user', to='User.T_user_info')),
            ],
        ),
    ]
