# Generated by Django 3.0.2 on 2021-01-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0004_auto_20210109_1630'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchase_history',
            name='purchase_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='t_purchase_history',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_history_category_id', to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_purchase_history',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_history_user', to='User.T_user_info'),
        ),
        migrations.AlterField(
            model_name='t_purchase_state',
            name='current_state',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='t_purchase_state',
            name='expiry_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='t_purchase_state',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_state_category_idcategory', to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_purchase_state',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_state_user', to='User.T_user_info'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='question_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='Examination.T_question_category'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='score',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='test_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='test_paper_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_paper', to='Examination.T_test_paper'),
        ),
        migrations.AlterField(
            model_name='t_test_info',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='User.T_user_info'),
        ),
        migrations.AlterField(
            model_name='t_user_info',
            name='identity_card',
            field=models.CharField(default=None, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='t_user_info',
            name='login_state',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='t_user_info',
            name='permission',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='t_user_info',
            name='phone_number',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='t_user_info',
            name='registration_date',
            field=models.DateTimeField(default=None),
        ),
    ]
