# Generated by Django 3.0.2 on 2021-01-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210109_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user_info',
            name='login_state',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
