# Generated by Django 3.0.2 on 2021-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210109_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user_info',
            name='permission',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
