# Generated by Django 3.0.2 on 2021-01-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0007_auto_20210110_1246'),
        ('User', '0004_auto_20210109_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_test_info',
            old_name='test_paper_id',
            new_name='test_paper',
        ),
        migrations.RenameField(
            model_name='t_test_info',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='t_purchase_history',
            name='question_category_id',
        ),
        migrations.RemoveField(
            model_name='t_purchase_history',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='t_purchase_state',
            name='question_category_id',
        ),
        migrations.RemoveField(
            model_name='t_purchase_state',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='t_test_info',
            name='question_category_id',
        ),
        migrations.AddField(
            model_name='t_purchase_history',
            name='question_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_history_question_category_id', to='Examination.T_question_category'),
        ),
        migrations.AddField(
            model_name='t_purchase_history',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_history_user_id', to='User.T_user_info'),
        ),
        migrations.AddField(
            model_name='t_purchase_state',
            name='question_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_state_question_category_id', to='Examination.T_question_category'),
        ),
        migrations.AddField(
            model_name='t_purchase_state',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='T_purchase_state_user_id', to='User.T_user_info'),
        ),
        migrations.AddField(
            model_name='t_test_info',
            name='question_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_category', to='Examination.T_question_category'),
        ),
    ]
